-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('USER', 'MAX') NOT NULL DEFAULT 'USER';

-- AddForeignKey
ALTER TABLE `Strategy` ADD CONSTRAINT `Strategy_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
